@echo off
setlocal
cd /d "%~dp0"
rem ==================================================================
rem  Build script.  IMPORTANT: keep every line in this file ASCII.
rem  cmd.exe decodes .bat files with the console code page, and javac
rem  reads @argfiles with the JVM default charset; if either meets
rem  non-ASCII bytes you get MalformedInputException / "file not found".
rem  The source list is therefore generated by tools\GenList.java with
rem  the SAME JVM that runs javac, and it contains ASCII relative paths.
rem ==================================================================
set LIB=lib\pdfbox-3.0.3.jar;lib\fontbox-3.0.3.jar;lib\pdfbox-io-3.0.3.jar;lib\commons-logging-1.3.4.jar
if exist build rmdir /s /q build
mkdir build
java -Dfile.encoding=UTF-8 tools\GenList.java build\sources.txt src
if errorlevel 1 goto fail
javac -encoding UTF-8 -cp "%LIB%" -d build @build\sources.txt
if errorlevel 1 goto fail
echo.
echo Build OK.  Run: run.bat
pause
exit /b 0
:fail
echo.
echo Build FAILED - install a JDK first (check: javac -version).
pause
exit /b 1